# Generated by Django 5.1.6 on 2025-02-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alter", models.IntegerField()),
                ("urlaubstage", models.IntegerField()),
                ("gehalt", models.FloatField()),
                ("geschlecht", models.CharField(max_length=100)),
            ],
        ),
    ]
