# Generated by Django 5.1.6 on 2025-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
