# Generated by Django 5.1.6 on 2025-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikestore', '0002_alter_worker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modell', models.CharField(max_length=100)),
                ('zoll', models.IntegerField()),
                ('typ', models.CharField(max_length=100)),
                ('farbe', models.CharField(max_length=100)),
                ('anzahl', models.IntegerField()),
                ('kosten', models.FloatField()),
                ('verkaeufe', models.IntegerField()),
                ('vorraetig', models.IntegerField()),
            ],
        ),
    ]
